
export const weapons = [
  {
    id: 'pistol',
    name: 'pistol',
    category: '9mm Semi-Auto',
    tag: 'M1',
    image: '/images/pistol.png',
    file: '/sounds/pistol.wav',
  },
  {
    id: 'revolver',
    name: 'revolver',
    category: '.357 Revolver',
    tag: 'M2',
    image: '/images/revolver.png',
    file: '/sounds/revolver.wav',
  },
  {
    id: 'shotgun',
    name: 'shotgun',
    category: '12 Gauge Pump',
    tag: 'M3',
    image: '/images/shotgun.png',
    file: '/sounds/shotgun.wav',
  },
  {
    id: 'rifle',
    name: 'Assault Rifle',
    category: '5.56 Select-Fire',
    tag: 'M4',
    image: '/images/rifle.png',
    shots: 3,
    interval: 0.09,
    file: '/sounds/rifle.wav',
  },
  {
    id: 'sniper',
    name: 'sniper',
    category: '.308 Bolt-Action',
    tag: 'M5',
    image: '/images/sniper.png',
    file: '/sounds/sniper.wav',
  },
  {
    id: 'smg',
    name: 'smg',
    category: '9mm Full-Auto',
    tag: 'M6',
    image: '/images/smg.png',
    shots: 6,
    interval: 0.065,
    file: '/sounds/smg.wav',
  },
]
